ELF: add ET_NONE, add several more machine types
kaitai-io/kaitai_struct_formats pull request #455
Opened 2021-03-20 19:42 UTC by armijnhemel

Add ET_NONE type, plus a few machine types. I have seen most of these in real life, and recently.

2021-03-21 02:18 UTC, KOLANICH approved these changes
You may find https://github.com/KOLANICH-libs/ELFMachine.py useful for an autogenerate script.

2021-03-21 11:30 UTC, armijnhemel commented
> You may find https://github.com/KOLANICH-libs/ELFMachine.py useful for an autogenerate script.

I have cherry picked only the few that I am seeing in real life as to not clutter the file. Of course, if there is a need to be complete, then I will add them all.

2021-03-21 11:34 UTC, generalmimon requested changes

2021-03-21 11:35 UTC, armijnhemel commented on executable/elf.ksy
>      0xB7: aarch64
The original specification was uppercase. I will convert to lowercase.

2021-03-21 11:40 UTC, generalmimon commented on executable/elf.ksy
>      0xB7: aarch64
> The original specification was uppercase. I will convert to lowercase.

So what is the original specification? There is only this one in `/doc-ref`:

https://github.com/kaitai-io/kaitai_struct_formats/blob/e6bebab40a1d73a8608d229700f5c1a8004adea6/executable/elf.ksy#L24

2021-03-21 12:10 UTC, armijnhemel commented on executable/elf.ksy
>      0xB7: aarch64
I meant the original kaitai struct specification. Wrong choice of words ;)

2021-03-21 12:14 UTC, armijnhemel commented on executable/elf.ksy
> +    0: no_file_type
The official ELF specitication found at https://refspecs.linuxfoundation.org/elf/elf.pdf on page 18 says "no file type".

2021-03-21 12:16 UTC, generalmimon commented on executable/elf.ksy
> +    0: no_file_type
Yeah, that's a different meaning, sorry for the silly suggestion.

2021-03-21 12:16 UTC, armijnhemel commented on executable/elf.ksy
> +    0: no_file_type
Page 19 of the official spec says it should be "no machine" instead of "not set".

2021-03-21 12:18 UTC, generalmimon commented on executable/elf.ksy
> +    0: no_file_type
> Page 19 of the official spec says it should be "no machine" instead of "not set".

Good catch - this means it should be updated too, then.

2021-03-21 12:19 UTC, generalmimon commented on executable/elf.ksy
>      0xB7: aarch64
Actually, I don't actually understand why the enum integer keys are written in hex in the KSY while they are specified in decimal base in both https://refspecs.linuxfoundation.org/elf/elf.pdf and https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/elf.h;hb=HEAD.

2021-03-21 12:20 UTC, armijnhemel commented on executable/elf.ksy
>      0xB7: aarch64
> Actually, I don't actually understand why the enum integer keys are written in hex in the KSY while they are specified in decimal base in both https://refspecs.linuxfoundation.org/elf/elf.pdf and https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/elf.h;hb=HEAD.

Me neither. I just copied what was already there :)

2021-03-21 17:53 UTC, generalmimon approved these changes
Thanks!

2021-03-21 17:53 UTC, merged

2021-03-24 20:35 UTC, armijnhemel commented
Just for documentation purposes, on my Fedora machine the following file has "no machine":

```
$ file /usr/lib64/guile/2.2/ccache/scripts/api-diff.go
/usr/lib64/guile/2.2/ccache/scripts/api-diff.go: ELF 64-bit LSB shared object, no machine, version 1 (embedded), dynamically linked, with debug_info, not stripped
```